#!/bin/bash +e
#
# Author: Darryl Abbate
# https://github.com/rootbeersoup/ghost
#
# All-in-one Homebrew maintenance script
# - Installs Homebrew if missing
# - Installs packages from global Brewfile (~/.Brewfile)
# - Updates formulae
# - Upgrades existing packages
# - Cleans up formulae

# shellcheck disable=SC2059

BUNDLELOG=$(mktemp /tmp/ghost.bundle.check.XXXXXXXX)
INSTALLLOG=$(mktemp /tmp/ghost.bundle.install.XXXXXXXX)
OUTDATEDLOG=$(mktemp /tmp/ghost.outdated.XXXXXXXX)
UPDATELOG=$(mktemp /tmp/ghost.update.XXXXXXXX)
UPGRADELOG=$(mktemp /tmp/ghost.upgrade.XXXXXXXX)

CHECKMARK="\\033[32m✓\\033[0m"
CLEARLINE="\\033[2K"
ERRORMSG="\\033[31mERROR:\\033[0m"
SPINDELAY="0.05"
SPINSTR="⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

# Spinner function
spinner() 
{
  local PROCESS
  local POSTMSG

  PROCESS=$1
  POSTMSG=$2

  while :; do
    jobs %1 &> /dev/null
    [[ "$?" = 0 ]] ||
    {
      printf "${CLEARLINE}${CHECKMARK} ${POSTMSG}\\n"
      break
    }
    for (( i=0; i<${#SPINSTR}; i++ )); do
      sleep "$SPINDELAY"
      printf "${CLEARLINE}${SPINSTR:$i:1} ${PROCESS}\\r"
    done
  done
}

# Hanging spinner for commands preceding if statements
# Must be followed by else statement with proper `printf` message
spinner_hang() 
{
  local PROCESS

  PROCESS=$1

  while :; do
    jobs %1 &> /dev/null
    [[ "$?" = 0 ]] || break
    for (( i=0; i<${#SPINSTR}; i++ )); do
      sleep "$SPINDELAY"
      printf "${CLEARLINE}${SPINSTR:$i:1} ${PROCESS}\\r"
    done
  done
}

# trap function for 0 exit codes
finish()
{
  tput cnorm
  exit 0
}

# trap function for user interrupts
interrupt()
{
  printf "\\n\\033[31m✗\\033[0m User interrupt; terminating...\\n"
  tput cnorm
  exit 2
}

print_install_log()
{
  local INSTALLEDPKGS
  
  INSTALLEDPKGS=$(grep -i installing "$INSTALLLOG" | awk '{print "  \033[34m|\033[0m "$2}')

  printf "${INSTALLEDPKGS}\\n"
}

print_upgrade_log()
{
  local UPGSUMMARY
  
  UPGSUMMARY=$(awk 'FNR == 2 {print}' "$UPGRADELOG" | sed $'s/, /\\\n/g' | column -t | awk '{print "  \033[34m|\033[0m "$0}')

  printf "${UPGSUMMARY}\\n"
}

# Brew Bundle
brew_bundle()
{
  # Skip brew bundle if no Brewfile found
  if ! [[ -f "$HOME/.Brewfile" ]]; then
    printf "${ERRORMSG} Global Brewfile not found (~/.Brewfile).\\n       Skipping \`brew bundle\`...\\n"
  else
    # Run `brew bundle check` since it's quicker than `brew bundle`
    # For whatever reason, `bundle check` always returns "missing dependencies" unless using the `--verbose` flag
    (brew bundle check --global --verbose > "$BUNDLELOG") &
    spinner_hang "Check Brewfile for missing packages" 

    # Run `brew bundle` if `check` returns missing dependencies
    if [[ $(grep missing "$BUNDLELOG" &> /dev/null; echo $?) -eq 0 ]]; then
      (brew bundle --global > "$INSTALLLOG") &
      spinner "Install missing packages" "New packages installed"
      print_install_log
      rm "$INSTALLLOG"
    fi
    rm "$BUNDLELOG"
  fi
}

brew_update()
{
  (brew update > "$UPDATELOG") &
  spinner_hang "Update Homebrew formulae"

  if [[ $(wc -l "$UPDATELOG" | awk '{print $1}') -ge "2" ]]; then
    printf "${CLEARLINE}${CHECKMARK} Formulae updated\\n"
  fi
  rm "$UPDATELOG"
}

brew_upgrade()
{
  (brew outdated > "$OUTDATEDLOG") &
  spinner_hang "Check for available upgrades"

  if [[ -s "$OUTDATEDLOG" ]]; then
    (brew upgrade --display-times > "$UPGRADELOG") &
    spinner "Upgrade existing Homebrew packages" "Packages upgraded"
    print_upgrade_log
    rm "$OUTDATEDLOG"
    rm "$UPGRADELOG"
  fi
}
    
main()
{
  # Clean up upon 0 exit status
  trap finish 0

  # Clean up upon user interrupt (CTRL+C)
  trap interrupt 2

  # Exit quickly if run on something other than macOS
  if ! [[ "$(uname -s)" == "Darwin" ]]; then
    printf "${ERRORMSG} macOS required to use Homebrew\\n"
    exit 1
  fi

  # Install Homebrew if not already installed
  if ! [[ -x "$(command -v brew)" ]]; then 
    printf "Homebrew not found on this system; Installing...\\n"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  tput civis

  # Update
  brew_update

  # Upgrade
  brew_upgrade

  # Bundle
  brew_bundle

  # Cleanup
  (brew cleanup &> /dev/null) &
  spinner_hang "Clean up"

  # Done
  printf "${CLEARLINE}${CHECKMARK} Homebrew up-to-date 🍺\\n"

  find /tmp/ -empty -name "ghost.*" -delete
}

main
